/* This file is autogenerated, do not edit, changes will be lost! */
#ifndef BOARD_CFG_H
#define BOARD_CFG_H (1)

/* === BOARD TYPES === */
#define BOARD_ZGBT1281A2UART1 (0)
#define BOARD_ICS230_12 (1)
#define BOARD_ICM230_12C (2)
#define BOARD_ZGBT1281A2UART0 (3)
#define BOARD_STKM8 (4)
#define BOARD_ICM230_11 (5)
#define BOARD_ICM230_12A (6)
#define BOARD_ICM230_12B (7)
#define BOARD_ICS230_11 (8)
#define BOARD_WDBA1281 (9)
#define BOARD_MNB900 (10)
#define BOARD_MUSE231 (11)
#define BOARD_ICT230 (12)
#define BOARD_IBDT232 (13)
#define BOARD_STB230 (14)
#define BOARD_STB230B (15)
#define BOARD_STB231 (16)
#define BOARD_STB212 (17)
#define BOARD_IBDT212 (18)
#define BOARD_RADIOFARO (19)
#define BOARD_RADIOFARO_V1 (20)
#define BOARD_STKM16 (21)
#define BOARD_CBB230 (22)
#define BOARD_CBB230B (23)
#define BOARD_CBB231 (24)
#define BOARD_CBB212 (25)
#define BOARD_CBB232 (26)
#define BOARD_ZGBH230 (27)
#define BOARD_ZGBH231 (28)
#define BOARD_ZGBH212 (29)
#define BOARD_ROSE231 (30)
#define BOARD_IM240A (31)
#define BOARD_IBDT231 (32)
#define BOARD_RBB230 (33)
#define BOARD_RBB230B (34)
#define BOARD_RBB231 (35)
#define BOARD_RBB212 (36)
#define BOARD_ANY900ST (37)
#define BOARD_ANY2400ST (38)
#define BOARD_PSK230 (39)
#define BOARD_PSK230B (40)
#define BOARD_PSK231 (41)
#define BOARD_PSK212 (42)
#define BOARD_PSK232 (43)
#define BOARD_RBB128RFA1 (44)
#define BOARD_RDK230 (45)
#define BOARD_RDK230B (46)
#define BOARD_RDK231 (47)
#define BOARD_RDK212 (48)
#define BOARD_RDK232 (49)
#define BOARD_RZUSB (50)
#define BOARD_RAVRF230A (51)
#define BOARD_RAVRF230B (52)
#define BOARD_DERFA1 (53)
#define BOARD_LGEE231 (54)
#define BOARD_BITBEAN (55)
#define BOARD_IM240A_EVAL (56)
#define BOARD_XXO (57)
#define BOARD_ZGBL230 (58)
#define BOARD_ZGBL231 (59)
#define BOARD_ZGBL212 (60)
#define BOARD_STB128RFA1 (61)
#define BOARD_LGEE231_V2 (62)
#define BOARD_ZIGDUINO (63)
#define BOARD_TINY230 (64)
#define BOARD_TINY231 (65)
#define BOARD_ZGBT1281A2NOUART (66)
#define BOARD_ANY900 (67)
#define BOARD_ANY2400 (68)

/* === BOARD INCLUDES === */
#if defined(zgbt1281a2uart1)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_zgbta2.h"

#elif defined(ics230_12) || defined(icm230_12c)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_ict_11.h"

#elif defined(zgbt1281a2uart0)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_zgbta2.h"

#elif defined(stkm8)
# define BOOT_LOADER_ADDRESS (0x0)
# include "boards/board_stkm8.h"

#elif defined(icm230_11) || defined(icm230_12a) || defined(icm230_12b)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_ict_11.h"

#elif defined(ics230_11)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_ict_11.h"

#elif defined(wdba1281) || defined(mnb900)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_wdba1281.h"

#elif defined(muse231)
# define BOOT_LOADER_ADDRESS (0xc00)
# include "boards/board_muse231.h"

#elif defined(ict230)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_ict230.h"

#elif defined(ibdt232)
# define BOOT_LOADER_ADDRESS (0x7800)
# include "boards/board_ibdt.h"

#elif defined(stb230) || defined(stb230b) || defined(stb231) || defined(stb212)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_stb.h"

#elif defined(ibdt212)
# define BOOT_LOADER_ADDRESS (0x7800)
# include "boards/board_ibdt.h"

#elif defined(radiofaro) || defined(radiofaro_v1)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_derfa.h"

#elif defined(sparkfun)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_sparkfun.h"

#elif defined(stkm16)
# define BOOT_LOADER_ADDRESS (0x1c00)
# include "boards/board_stkm16.h"

#elif defined(cbb230) || defined(cbb230b) || defined(cbb231) || defined(cbb212) || defined(cbb232)
# define BOOT_LOADER_ADDRESS (0x0)
# include "boards/board_cbb2xx.h"

#elif defined(zgbh230) || defined(zgbh231) || defined(zgbh212)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_zgbl.h"

#elif defined(rose231)
# define BOOT_LOADER_ADDRESS (0x3c00)
# include "boards/board_rose231.h"

#elif defined(im240a)
# define BOOT_LOADER_ADDRESS (0x0)
# include "boards/board_wimod.h"

#elif defined(ibdt231)
# define BOOT_LOADER_ADDRESS (0x7800)
# include "boards/board_ibdt.h"

#elif defined(rbb230) || defined(rbb230b) || defined(rbb231) || defined(rbb212)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_rbb.h"

#elif defined(any900st) || defined(any2400st)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_any.h"

#elif defined(psk230) || defined(psk230b) || defined(psk231) || defined(psk212) || defined(psk232)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_stk541.h"

#elif defined(rbb128rfa1)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_rbbrfa1.h"

#elif defined(rdk230) || defined(rdk230b) || defined(rdk231) || defined(rdk212) || defined(rdk232)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_rdk230.h"

#elif defined(rzusb)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_rzusb.h"

#elif defined(ravrf230a) || defined(ravrf230b)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_ravrf.h"

#elif defined(derfa1)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_derfa.h"

#elif defined(lgee231)
# define BOOT_LOADER_ADDRESS (0xc00)
# include "boards/board_lgee.h"

#elif defined(bitbean)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_wdba1281.h"

#elif defined(im240a_eval)
# define BOOT_LOADER_ADDRESS (0x0)
# include "boards/board_wimod.h"

#elif defined(xxo)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_derfa.h"

#elif defined(zgbl230) || defined(zgbl231) || defined(zgbl212)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_zgbl.h"

#elif defined(stb128rfa1)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_stbrfa1.h"

#elif defined(lgee231_v2)
# define BOOT_LOADER_ADDRESS (0xc00)
# include "boards/board_lgee.h"

#elif defined(zigduino)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_derfa.h"

#elif defined(tiny230) || defined(tiny231)
# define BOOT_LOADER_ADDRESS (0x0)
# include "boards/board_tiny230.h"

#elif defined(zgbt1281a2nouart)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_zgbta2.h"

#elif defined(any900) || defined(any2400)
# define BOOT_LOADER_ADDRESS (0xf000)
# include "boards/board_any.h"

#else
# error "BOARD_TYPE is not defined or wrong"
#endif

#endif /*BOARD_CFG_H*/
